import { useEffect, useState } from "react";
import { ArrowRight, Check, Menu, Palette, X } from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteLogo } from "@/components/SiteLogo";
import { ThemeSelector } from "@/components/ThemeSelector";

const contact = "https://wa.me/5511999999999?text=Ol%C3%A1%2C%20quero%20conversar%20com%20a%20VELTRION%20sobre%20um%20projeto%20digital.";
const links = [["Início", "#inicio"], ["Soluções", "#solucoes"], ["Projetos", "#projetos"], ["Como funciona", "#processo"], ["Conheça a VELTRION", "#sobre"]];
const services = [
  ["01", "Criação de sites", "Sites institucionais modernos, profissionais e responsivos, alinhados à identidade da sua empresa.", "Para apresentar sua marca, serviços, portfólio e formas de contato."],
  ["02", "Landing pages", "Páginas objetivas para apresentar ofertas, campanhas, produtos e serviços com clareza.", "Para facilitar que visitantes interessados se tornem novos contatos."],
  ["03", "Cardápios digitais", "Cardápios organizados, atraentes e preparados para uma boa experiência no celular.", "Para restaurantes e estabelecimentos apresentarem produtos com mais praticidade."],
  ["04", "Artes e materiais promocionais", "Peças visuais para comunicar produtos, campanhas, ofertas e necessidades comerciais.", "Para redes sociais, divulgações, apresentações e materiais digitais."],
  ["05", "Estratégia e soluções com IA", "Pesquisa, planejamento e ferramentas de inteligência artificial a serviço de ideias mais bem direcionadas.", "Para apoiar a criação e aprimorar a apresentação do seu negócio."],
];
const projects = [["Site institucional", "Uma vitrine digital clara para serviços, diferenciais e contato.", "site"], ["Landing page", "Uma página focada em uma oferta, campanha ou lançamento.", "landing"], ["Cardápio digital", "Uma experiência prática para explorar produtos pelo celular.", "menu"], ["Material promocional", "Peças visuais para comunicar uma campanha com consistência.", "art"]];

export function VeltrionHome() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { document.body.style.overflow = menuOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen]);
  const closeMenu = () => setMenuOpen(false);
  return <main className="min-h-screen bg-background text-foreground selection:bg-[#a8c6b8] selection:text-[#1e2c26]">
    <header className={`fixed inset-x-0 top-0 z-50 border-b transition-all duration-300 ${scrolled || menuOpen ? "border-zinc-200/80 bg-white/95 backdrop-blur-xl dark:border-white/10 dark:bg-[#121817]/95" : "border-transparent bg-white/80 backdrop-blur-md dark:bg-[#121817]/80"}`}><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-12"><a href="#inicio" onClick={closeMenu} className="flex items-center gap-3" aria-label="VELTRION — Início"><SiteLogo size={34} /><span className="text-[17px] font-bold tracking-[0.16em] text-zinc-900 dark:text-white">VELTRION</span></a><nav className="hidden items-center gap-7 text-sm font-medium text-zinc-600 dark:text-zinc-300 md:flex">{links.map(([label, href]) => <a key={href} href={href} className="transition-colors hover:text-[#547565]">{label}</a>)}</nav><div className="hidden items-center gap-4 md:flex"><ThemeSelector /><a href={contact} target="_blank" rel="noreferrer" className="rounded-full bg-[#1e2c26] px-5 py-3 text-sm font-semibold text-white transition-colors hover:bg-[#547565] dark:bg-[#d9e5df] dark:text-[#1e2c26]">Solicitar orçamento</a></div><div className="flex items-center gap-1 md:hidden"><ThemeSelector /><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="grid size-11 place-items-center rounded-full text-zinc-900 dark:text-white" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"}>{menuOpen ? <X /> : <Menu />}</button></div></div>{menuOpen && <div className="border-t border-zinc-200 bg-white px-5 py-6 dark:border-white/10 dark:bg-[#121817] md:hidden"><nav className="flex flex-col text-lg font-medium">{links.map(([label, href]) => <a key={href} onClick={closeMenu} href={href} className="border-b border-zinc-100 py-4 dark:border-white/10">{label}</a>)}</nav><a onClick={closeMenu} href={contact} target="_blank" rel="noreferrer" className="mt-6 flex justify-center rounded-full bg-[#1e2c26] px-5 py-3.5 font-semibold text-white">Falar com a VELTRION</a></div>}</header>
    <section id="inicio" className="relative overflow-hidden pt-36 sm:pt-44"><div className="absolute right-0 top-0 -z-0 h-[620px] w-[58%] bg-[#eef2ef] dark:bg-[#18221e]" /><div className="relative z-10 mx-auto grid max-w-7xl gap-12 px-5 pb-20 sm:px-8 lg:grid-cols-12 lg:items-end lg:px-12 lg:pb-28"><div className="lg:col-span-8"><p className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.16em] text-[#547565]"><span className="h-px w-9 bg-[#547565]" />Soluções digitais para empresas</p><h1 className="max-w-5xl text-4xl font-semibold leading-[1.07] tracking-[-0.045em] text-zinc-900 dark:text-white sm:text-6xl lg:text-7xl">Sua empresa merece uma presença digital <em className="font-serif font-normal text-[#547565]">à altura.</em></h1></div><div className="lg:col-span-4"><p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-300 sm:text-lg">A VELTRION transforma necessidades de negócio em soluções digitais profissionais, combinando tecnologia, estratégia, inteligência artificial e criatividade.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row lg:flex-col xl:flex-row"><a href="#solucoes" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#1e2c26] px-5 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-[#547565] dark:bg-[#d9e5df] dark:text-[#1e2c26]">Conhecer nossas soluções <ArrowRight className="size-4" /></a><a href={contact} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center rounded-full border border-[#547565] px-5 py-3.5 text-sm font-semibold text-[#294238] dark:text-[#d9e5df]">Falar com a VELTRION</a></div></div></div><div className="relative z-10 mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="relative overflow-hidden bg-[#1e2c26] px-7 py-10 text-white sm:px-12 sm:py-14"><div className="absolute -right-16 -top-28 size-96 rounded-full border border-white/15" /><div className="relative grid gap-8 lg:grid-cols-12"><p className="text-2xl leading-tight sm:text-3xl lg:col-span-7">Presença digital bem construída para apresentar melhor o que sua empresa faz.</p><p className="text-sm leading-relaxed text-[#c4d6cb] lg:col-span-4 lg:col-start-9">Do primeiro direcionamento à entrega, criamos materiais digitais claros, funcionais e coerentes com a sua marca.</p></div></div></div></section>
    <section id="solucoes" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32 lg:px-12"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Soluções</p><h2 className="mt-5 text-4xl font-semibold leading-[1.1] tracking-[-0.04em] sm:text-5xl">O que sua empresa precisa para se apresentar melhor no digital.</h2></div><p className="self-end text-base leading-relaxed text-zinc-600 dark:text-zinc-300 lg:col-span-4 lg:col-start-9">Serviços definidos para resolver necessidades reais de comunicação, presença e apresentação online.</p></div><div className="mt-16 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map(([number, title, text, example]) => <article key={number} className="group flex min-h-72 flex-col border border-zinc-200 p-7 transition-colors hover:border-[#92ac9e] dark:border-white/15 dark:hover:border-[#638373]"><div className="flex items-start justify-between"><span className="text-xs font-bold tracking-[0.16em] text-[#547565]">{number}</span><Palette className="size-5 text-[#547565]" /></div><h3 className="mt-10 text-2xl font-medium tracking-[-0.03em]">{title}</h3><p className="mt-3 text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">{text}</p><p className="mt-auto pt-6 text-xs font-medium leading-relaxed text-[#547565]">{example}</p></article>)}</div></section>
    <section id="projetos" className="bg-[#f3f4f1] py-24 dark:bg-[#18201d] sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Projetos e exemplos</p><h2 className="mt-5 max-w-2xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Formatos que podemos criar para o seu negócio.</h2></div><span className="text-sm text-zinc-600 dark:text-zinc-300">Demonstrações visuais</span></div><p className="mt-5 max-w-2xl text-base leading-relaxed text-zinc-600 dark:text-zinc-300">Estes exemplos conceituais mostram possibilidades de apresentação. Eles não representam trabalhos realizados para clientes.</p><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{projects.map(([title, description, type], index) => <article key={title} className="overflow-hidden border border-[#d7dfd9] bg-white p-4 dark:border-white/10 dark:bg-[#22302a]"><div className={`relative h-48 overflow-hidden bg-[#d9e5df] p-4 ${type === "landing" ? "bg-[#e8e1d7]" : ""} ${type === "menu" ? "bg-[#dce2eb]" : ""} ${type === "art" ? "bg-[#e5ddd2]" : ""}`}><div className="absolute inset-x-4 top-4 h-3 rounded-full bg-[#1e2c26]/80" /><div className="absolute left-4 top-11 h-12 w-3/5 rounded bg-white/75" />{type === "menu" ? <div className="absolute bottom-4 left-4 right-4 space-y-2">{[1, 2, 3].map(item => <div key={item} className="h-5 rounded bg-white/75" />)}</div> : <><div className="absolute bottom-4 left-4 h-14 w-[42%] rounded bg-[#547565]/70" /><div className="absolute bottom-4 right-4 h-14 w-[45%] rounded bg-white/75" /></>}</div><p className="mt-5 text-xs font-bold uppercase tracking-[0.14em] text-[#547565]">Exemplo {String(index + 1).padStart(2, "0")}</p><h3 className="mt-2 text-xl font-medium tracking-[-0.02em]">{title}</h3><p className="mt-2 text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">{description}</p></article>)}</div></div></section>
    <section id="processo" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32 lg:px-12"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Como funciona</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Um processo simples, com clareza em cada etapa.</h2></div><div className="lg:col-span-7 lg:col-start-6"><div className="space-y-8">{[["01", "Entendimento", "Conhecemos a empresa e a necessidade que precisa ser resolvida."], ["02", "Planejamento", "Definimos a melhor solução para o objetivo apresentado."], ["03", "Criação", "Desenvolvemos o material ou projeto digital com atenção aos detalhes."], ["04", "Entrega", "Apresentamos o resultado e conduzimos os ajustes combinados."]].map(([number, title, text]) => <div key={number} className="grid grid-cols-[52px_1fr] gap-5 border-t border-zinc-200 pt-6 dark:border-white/15"><span className="font-serif text-xl text-[#547565]">{number}</span><div><h3 className="text-xl font-medium tracking-[-0.02em]">{title}</h3><p className="mt-2 max-w-lg text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">{text}</p></div></div>)}</div></div></div></section>
    <section id="sobre" className="bg-[#1e2c26] py-24 text-white sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a8c6b8]">Conheça a VELTRION</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.1] tracking-[-0.04em] sm:text-5xl">Soluções digitais que representam melhor a sua empresa.</h2></div><div className="space-y-6 text-base leading-relaxed text-[#d7e1dc] lg:col-span-4 lg:col-start-9"><p>A VELTRION ajuda empresas a melhorar sua presença digital por meio de tecnologia, estratégia, inteligência artificial e criatividade.</p><p>Transformamos necessidades de negócio em experiências digitais mais claras, profissionais e funcionais. Nosso trabalho começa pela compreensão do que cada empresa precisa, passa pela melhor direção e termina em uma solução que represente sua marca.</p><div className="space-y-3 pt-2 text-sm">{["Escuta para entender o contexto", "Direção para definir o caminho", "Criação para dar forma à solução"].map(item => <p key={item} className="flex gap-3"><Check className="mt-0.5 size-4 shrink-0 text-[#a8c6b8]" />{item}</p>)}</div></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="flex flex-col items-start justify-between gap-8 border-y border-zinc-200 py-12 dark:border-white/15 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Vamos conversar</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Conte o que sua empresa precisa criar.</h2><p className="mt-3 text-sm text-zinc-600 dark:text-zinc-300">Fale com a VELTRION para solicitar um orçamento.</p></div><a href={contact} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-[#1e2c26] px-6 py-3.5 text-sm font-semibold text-white transition-colors hover:bg-[#547565] dark:bg-[#d9e5df] dark:text-[#1e2c26]">Solicitar orçamento <ArrowRight className="size-4" /></a></div></section><SiteFooter />
  </main>;
}
