import { useEffect, useState } from "react";
import { ArrowRight, Compass, Menu, MonitorSmartphone, Palette, Sparkles, X } from "lucide-react";
import { SiteFooter } from "@/components/SiteFooter";
import { SiteLogo } from "@/components/SiteLogo";
import { ThemeSelector } from "@/components/ThemeSelector";

const contact = "https://wa.me/5511999999999?text=Ol%C3%A1%2C%20quero%20conversar%20com%20a%20VELTRION%20sobre%20um%20projeto%20digital.";
const links = [["Início", "#inicio"], ["Soluções", "#solucoes"], ["Projetos", "#projetos"], ["Como funciona", "#processo"], ["Sobre a VELTRION", "#sobre"]];
const solutions = [["01", "Presença digital", "Sites institucionais e plataformas que organizam sua mensagem e dão solidez à sua marca."], ["02", "Experiências de conversão", "Landing pages e campanhas pensadas para transformar interesse em conversas qualificadas."], ["03", "Identidade em movimento", "Direção visual e materiais digitais que tornam cada ponto de contato mais consistente."]];
const projects = [["Estratégia digital", "Uma presença que traduz ambição.", "bg-[#d9e5df] dark:bg-[#263d35]", "Posicionamento · Website · Conteúdo"], ["Experiência de marca", "Clareza para escolher. Interesse para avançar.", "bg-[#e8e1d7] dark:bg-[#40382d]", "Campanha · Landing page · Direção"], ["Sistema visual", "Coerência em cada nova oportunidade.", "bg-[#dce2eb] dark:bg-[#293544]", "Design · Comunicação · Escala"]];

export function VeltrionHome() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { document.body.style.overflow = menuOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen]);
  const closeMenu = () => setMenuOpen(false);
  return <main className="min-h-screen bg-background text-foreground selection:bg-[#a8c6b8] selection:text-[#1e2c26]">
    <header className={`fixed inset-x-0 top-0 z-50 border-b transition-all duration-300 ${scrolled || menuOpen ? "border-zinc-200/80 dark:border-white/10 bg-white/95 dark:bg-[#121817]/95 backdrop-blur-xl" : "border-transparent bg-white/80 dark:bg-[#121817]/80 backdrop-blur-md"}`}>
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-12">
        <a href="#inicio" onClick={closeMenu} className="flex items-center gap-3" aria-label="VELTRION — Início"><SiteLogo size={34} /><span className="text-[17px] font-bold tracking-[0.16em] text-zinc-900 dark:text-white">VELTRION</span></a>
        <nav className="hidden items-center gap-7 text-sm font-medium text-zinc-600 dark:text-zinc-300 md:flex">{links.map(([label, href]) => <a key={href} href={href} className="transition-colors hover:text-[#547565]">{label}</a>)}</nav>
        <div className="hidden items-center gap-4 md:flex"><ThemeSelector /><a href={contact} target="_blank" rel="noreferrer" className="rounded-full bg-[#1e2c26] px-5 py-3 text-sm font-semibold text-white hover:bg-[#547565] dark:bg-[#d9e5df] dark:text-[#1e2c26]">Iniciar conversa</a></div>
        <div className="flex items-center gap-1 md:hidden"><ThemeSelector /><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="grid size-11 place-items-center rounded-full text-zinc-900 dark:text-white" aria-label={menuOpen ? "Fechar menu" : "Abrir menu"}>{menuOpen ? <X /> : <Menu />}</button></div>
      </div>
      {menuOpen && <div className="border-t border-zinc-200 bg-white px-5 py-6 dark:border-white/10 dark:bg-[#121817] md:hidden"><nav className="flex flex-col text-lg font-medium">{links.map(([label, href]) => <a key={href} onClick={closeMenu} href={href} className="border-b border-zinc-100 py-4 dark:border-white/10">{label}</a>)}</nav><a onClick={closeMenu} href={contact} target="_blank" rel="noreferrer" className="mt-6 flex justify-center rounded-full bg-[#1e2c26] px-5 py-3.5 font-semibold text-white">Iniciar conversa</a></div>}
    </header>
    <section id="inicio" className="relative overflow-hidden pt-36 sm:pt-44"><div className="absolute right-0 top-0 -z-0 h-[580px] w-[56%] bg-[#eef2ef] dark:bg-[#18221e]" /><div className="relative z-10 mx-auto grid max-w-7xl gap-12 px-5 pb-20 sm:px-8 lg:grid-cols-12 lg:items-end lg:px-12 lg:pb-28"><div className="lg:col-span-7"><p className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.16em] text-[#547565]"><span className="h-px w-9 bg-[#547565]" />Estratégia · Design · Tecnologia</p><h1 className="max-w-4xl text-4xl font-semibold leading-[1.07] tracking-[-0.045em] text-zinc-900 dark:text-white sm:text-6xl lg:text-7xl">O digital da sua empresa com <em className="font-serif font-normal text-[#547565]">direção.</em></h1></div><div className="lg:col-span-4 lg:col-start-9"><p className="text-base leading-relaxed text-zinc-600 dark:text-zinc-300 sm:text-lg">Unimos pensamento estratégico, design preciso e tecnologia para transformar boas empresas em marcas digitais mais claras e relevantes.</p><a href={contact} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-3 border-b border-[#547565] pb-2 text-sm font-bold text-[#294238] dark:text-[#c4d6cb]">Conheça nossa abordagem <ArrowRight className="size-4" /></a></div></div><div className="relative z-10 mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="relative overflow-hidden bg-[#1e2c26] px-7 py-10 text-white sm:px-12 sm:py-14"><div className="absolute -right-16 -top-28 size-96 rounded-full border border-white/15" /><div className="relative grid gap-10 lg:grid-cols-12"><p className="text-2xl leading-tight sm:text-3xl lg:col-span-7">Construímos experiências que dão forma ao que sua empresa faz de melhor.</p><p className="text-sm leading-relaxed text-[#c4d6cb] lg:col-span-4 lg:col-start-9">Mais do que entregar telas, organizamos percepção, mensagem e crescimento em uma presença que sustenta próximos passos.</p></div></div></div></section>
    <section id="solucoes" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32 lg:px-12"><div className="grid gap-10 lg:grid-cols-12"><div className="lg:col-span-5"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Soluções</p><h2 className="mt-5 text-4xl font-semibold leading-[1.1] tracking-[-0.04em] sm:text-5xl">O necessário para sua marca avançar com consistência.</h2></div><p className="self-end text-base leading-relaxed text-zinc-600 dark:text-zinc-300 lg:col-span-4 lg:col-start-9">Cada projeto nasce de uma leitura cuidadosa do seu momento, da sua audiência e das decisões que precisam acontecer.</p></div><div className="mt-16 border-t border-zinc-200 dark:border-white/15">{solutions.map(([number, title, text], index) => <article key={number} className="group grid gap-5 border-b border-zinc-200 py-8 dark:border-white/15 sm:grid-cols-12 sm:items-center sm:gap-8"><span className="text-sm font-medium text-[#547565] sm:col-span-1">{number}</span><h3 className="text-2xl font-medium tracking-[-0.03em] sm:col-span-4">{title}</h3><p className="text-sm leading-relaxed text-zinc-600 dark:text-zinc-300 sm:col-span-5">{text}</p><span className="flex size-11 items-center justify-center rounded-full border border-zinc-300 text-[#547565] transition-colors group-hover:bg-[#547565] group-hover:text-white dark:border-white/20 sm:col-span-1">{index === 0 ? <MonitorSmartphone className="size-5" /> : index === 1 ? <Compass className="size-5" /> : <Palette className="size-5" />}</span></article>)}</div></section>
    <section id="projetos" className="bg-[#f3f4f1] py-24 dark:bg-[#18201d] sm:py-32"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-12"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Projetos</p><h2 className="mt-5 max-w-xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">O que muda quando tudo começa a conversar.</h2></div><a href={contact} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-[#294238] dark:text-[#c4d6cb]">Ver possibilidades <ArrowRight className="size-4" /></a></div><div className="mt-14 grid gap-5 md:grid-cols-3">{projects.map(([kind, title, tone, detail], index) => <article key={title} className={`${tone} min-h-100 p-7 sm:p-8 ${index === 1 ? "md:translate-y-10" : ""}`}><div className="flex justify-between text-xs font-bold uppercase tracking-[0.13em] text-[#435e50]"><span>{kind}</span><span>0{index + 1}</span></div><div className="mt-24 border-t border-[#557465]/30 pt-5"><h3 className="text-2xl font-medium leading-tight tracking-[-0.03em] text-[#1e2c26] dark:text-white">{title}</h3><p className="mt-5 text-xs uppercase tracking-wider text-[#435e50] dark:text-[#c4d6cb]">{detail}</p></div></article>)}</div></div></section>
    <section id="processo" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 sm:py-32 lg:px-12"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-4"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#547565]">Como funciona</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Um processo próximo, sem ruído.</h2></div><div className="lg:col-span-7 lg:col-start-6"><div className="space-y-9">{[["01", "Escuta e contexto", "Começamos entendendo cenário, prioridades e o que precisa mudar."], ["02", "Direção e construção", "Transformamos a estratégia em uma experiência visual clara e funcional."], ["03", "Refino e entrega", "Validamos detalhes e entregamos uma base preparada para crescer."]].map(([number, title, text]) => <div key={number} className="grid grid-cols-[52px_1fr] gap-5 border-t border-zinc-200 pt-6 dark:border-white/15"><span className="font-serif text-xl text-[#547565]">{number}</span><div><h3 className="text-xl font-medium tracking-[-0.02em]">{title}</h3><p className="mt-2 max-w-lg text-sm leading-relaxed text-zinc-600 dark:text-zinc-300">{text}</p></div></div>)}</div></div></div></section>
    <section id="sobre" className="bg-[#1e2c26] py-24 text-white sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 px-5 sm:px-8 lg:grid-cols-12 lg:px-12"><div className="lg:col-span-7"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a8c6b8]">Sobre a VELTRION</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.1] tracking-[-0.04em] sm:text-5xl">Uma parceira digital para empresas que sabem onde querem chegar.</h2></div><div className="space-y-6 text-base leading-relaxed text-[#d7e1dc] lg:col-span-4 lg:col-start-9"><p>A VELTRION existe para tornar a presença digital de empresas mais inteligente, mais elegante e mais útil para o negócio.</p><p>Trabalhamos com atenção ao contexto e rigor nos detalhes — porque confiança não é um efeito visual: é uma consequência de boas escolhas.</p><a href={contact} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border-b border-[#a8c6b8] pb-2 text-sm font-bold text-white">Falar sobre seu projeto <ArrowRight className="size-4" /></a></div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><div className="flex flex-col items-start justify-between gap-8 border-y border-zinc-200 py-12 dark:border-white/15 md:flex-row md:items-center"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-[#547565]"><Sparkles className="size-4" />Vamos conversar</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Seu próximo movimento começa aqui.</h2></div><a href={contact} target="_blank" rel="noreferrer" className="inline-flex items-center gap-3 rounded-full bg-[#1e2c26] px-6 py-3.5 text-sm font-semibold text-white hover:bg-[#547565] dark:bg-[#d9e5df] dark:text-[#1e2c26]">Iniciar conversa <ArrowRight className="size-4" /></a></div></section>
    <SiteFooter />
  </main>;
}
